- hosts: localhost
  gather_facts: no
  become: yes

  vars:
    apps:
      - name: "AdBlock"
        url: "https://adblockforchrome.github.io/mac/AdBlock.dmg"
      - name: "AdGuard for Safari"
        url: "https://adguard.com/d/13852/AdGuard-for-Safari-1.4.4-187.pkg"
      - name: "Adobe Acrobat Reader"
        url: "https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2101020033/AcrobatDCUpd2101020033.dmg"
      - name: "Alfred 4"
        url: "https://cachefly.alfredapp.com/Alfred_4.5_1240.dmg"
      - name: "AnyDesk"
        url: "https://download.anydesk.com/AnyDesk.dmg"
      - name: "AppCleaner"
        url: "https://freemacsoft.net/downloads/AppCleaner_3.5.zip"
      - name: "Archi"
        url: "https://www.archimatetool.com/downloads/archi/4.8/Archi-Mac-4.8.tgz"
      - name: "Asana"
        url: "https://asa.na/Asana.dmg"
      - name: "Automator"
      - name: "Bitwarden"
        url: "https://vault.bitwarden.com/download/?app=desktop&platform=macos"
      - name: "BlueJeans"
        url: "https://swdl.bluejeans.com/desktop-app/mac/2.23.1/2.23.1.2808/BlueJeansInstaller.pkg"
      - name: "Books"
      - name: "Buffer"
        url: "https://buffer.com/resources/downloads/buffer-mac.zip"
      - name: "Calculator"
      - name: "Calendar"
      - name: "CheatSheet"
        url: "https://mediaatelier.com/CheatSheet/CheatSheet_1.3.4.zip"
      - name: "Chess"
      - name: "Clock"
      - name: "Clocker"
        url: "https://github.com/n0shake/Clocker/releases/download/1.6.2/Clocker-1.6.2.dmg"
      - name: "Contacts"
      - name: "DemoPro"
        url: "https://www.demopro.com/downloads/DemoPro.dmg"
      - name: "Dictionary"
      - name: "Docker"
        url: "https://desktop.docker.com/mac/stable/Docker.dmg"
      - name: "Dozer"
        url: "https://github.com/Mortennn/Dozer/releases/download/v5.1.0/Dozer.app.zip"
      - name: "draw.io"
        url: "https://github.com/jgraph/drawio-desktop/releases/download/v15.5.4/draw.io-15.5.4-mac.dmg"
      - name: "Evernote"
        url: "https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_10.22.5_455707.zip"
      - name: "FaceTime"
      - name: "Fig"
        url: "https://withfig.com/downloads/fig-macos-latest.zip"
      - name: "Find My"
      - name:
