---
- name: Instalar aplicaciones en Mac
  hosts: localhost
  become: yes

  tasks:
    - name: Instalar Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

     - name: Instalar aplicaciones
      shell: |
        xargs brew cask install < /ruta/de/destino/en/tu/servidor/aplicaciones.txt
      args:
        executable: /bin/bash
      become: yes
      become_method: sudo
